### ISSUE TITLE
LO Event running TODO

### ISSUE THREAD

**Issue by bradley-erickson** [ETS-Next-Gen/writing_observer#103]
The LO Event package has been abstracted out, but there may be work left to do. Please leave any bugs, things not yet implemented, or other ideas in this issue.

- [ ] Ajax logger
- [ ] Opt in/out strategy
- [ ] Add ability to specify which verbs, nouns, etc. we might use
- [ ] Fix and test `queue.js` within a node environment
- [ ] Fix auto-increment within `queue.js` (currently resets to 0 each time)
- [ ] Ensure all events have `event` field - Websocket's onclose and onerror do not
- [ ] Implement blacklisting server side, test overall pipeline
- [ ] Update server-side code to handle lock_fields, metadata, auth, etc.
- [ ] Disable ability to send/store events if we are getting more than some number of exceptions
- [ ] Resolve any storage errors when importing lo_event in another non-extension node project
- [ ]
