### ISSUE TITLE
Login Redirect Workflow 

### ISSUE THREAD

**Issue by bradley-erickson** [ETS-Next-Gen/writing_observer#63]
We want to handle redirected the user properly when they are viewing a resource they are unable to. The current implementation, merged in in PR #59, redirects any unauthorized users to the home page (also the login page).

- [ ]  Indicate to user why they are being redirected #60 
- [ ]  Encode where user came from #61 so we can redirect them
- [ ]  Handle not logged in vs unauthorized properly #62
