### ISSUE TITLE
Extension improvements

### ISSUE THREAD

**Issue by bradley-erickson** [ETS-Next-Gen/writing_observer#64]
There are various improvements we want to make to the extension.

- [ ] Added a config to the extension #3 
- [ ] Figure out auth workflow #2 
- [ ] Added in queuing and batching #5 
- [ ] Set extension access security for non-Chrome logins. #15

**Comment by bradley-erickson** [comment]
- [ ] #194
